### ISSUE TITLE
Linked device creation fails - "Cannot create the linked device"

### ISSUE THREAD

**Issue by chpio** [mollyim/mollyim-android-unifiedpush#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Distributors tried:
 * ntfy (default server & self hosted)
 * conversations

Using the latest MollySocket docker image via docker-compose (although it does not change the outcome even if the server is offline). Enabling Air gapped mode results in a "No device" server parameters. Creating "real" linked devices is working tho.

### Steps to reproduce

1. Switch to WebSocket push
2. Switch back to UP push

### Molly version

v6.40.4-1.up1

### Android version

Android 14

### Device

Pixel 8 Pro running CalyxOs@5.2.0

### Link to debug log

https://debuglogs.org/android/6.40.4/7b307063030d44984295e92eazvf674d484df00898f8fd8ac36a7ba22bbdfa8

**Comment by seffs** [comment]
I encountered the same bug. I had a "mollysocket" linked device that was inactive (~3 weeks) because I never installed any sort of mollysocket server before. Molly prompted me to remove it and let it create a new one. 

Now I get the same error `"Cannot create the linked device"` over and over. I already tried reinstalling the app. My new webserver is also reachable (the check appears). Are Signal servers blocking the socket?

**Comment by jbruechert** [comment]
With commit 25b9c8b351a26e55645ce023517dbcbf31f737de, the error message has now changed to "unable to find the endpoint" for me.

**Comment by jbruechert** [comment]
edit: This only happens with the NextPush distributor, ntfy works

**Comment by p1gp1g** [comment]
Signal server removed the endpoint that was used to create the linked device. Fix: https://github.com/mollyim/mollyim-android-unifiedpush/commit/8541ce4adb7a760dd616ca7267bc226627c8d12e

And @JBBgameich, the conf doesn't depend on the distibutor. But if you selfhost your nextcloud server, add it to your allowed_endpoints: https://github.com/mollyim/mollysocket#allowed_endpoints
